# permissions for end users to edit pods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-editor-role
rules:
- apiGroups:
  - cnat.shivank.dev
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnat.shivank.dev
  resources:
  - pods/status
  verbs:
  - get
